import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getPatient } from "../../services/patientService";
import { patientDisplayName } from "../../data/patientFormData";

const fields = [["Status", "is_active"], ["Patient code", "patient_code"], ["Sex", "gender"], ["Birthdate", "date_of_birth"], ["Phone", "phone"], ["Identification type", "identification_type"], ["Identification number", "identification_number"], ["Disability", "disability"], ["Province", "province_id"], ["District", "district_id"], ["Commune", "commune_id"], ["Village", "village_id"], ["Created by", "created_by"], ["Modified by", "modified_by"], ["Created", "created_at"]];
export default function PatientViewPage() {
  const { patientId } = useParams(); const [patient, setPatient] = useState(null); const [error, setError] = useState("");
  useEffect(() => { getPatient(patientId).then((response) => setPatient(response.data?.patient || response.data || response.patient)).catch((requestError) => setError(requestError.message || "Could not load patient.")); }, [patientId]);
  if (error) return <section className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-rose-700">{error}</section>;
  if (!patient) return <section className="rounded-2xl border border-slate-200 bg-white p-12 text-center text-sm text-slate-500">Loading patient record…</section>;
  return <section className="mx-auto w-full max-w-5xl space-y-6"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold text-teal-600">Patients / Details</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-900">{patientDisplayName(patient) || "Patient details"}</h1><p className="mt-2 text-sm text-slate-500">Complete patient record</p></div><div className="flex gap-2"><Link to="/patients" className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50">Back</Link><Link to={`/patients/${patient.id}/edit`} className="rounded-xl bg-teal-700 px-4 py-2 text-sm font-semibold text-white hover:bg-teal-800">Edit</Link></div></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{fields.map(([label, key]) => <div key={key}><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm text-slate-800">{patient[key] ? (key === "date_of_birth" ? String(patient[key]).slice(0, 10) : key === "created_at" ? new Date(patient[key]).toLocaleString() : patient[key]) : "-"}</p></div>)}</div>{patient.photo && <div className="mt-6 border-t border-slate-100 pt-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Photo</p><a href={patient.photo} target="_blank" rel="noreferrer" className="mt-1 inline-block text-sm font-semibold text-teal-700 hover:underline">Open photo</a></div>}</div></section>;
}
